"""Initial migration

Revision ID: 8968edd7b050
Revises: 
Create Date: 2026-06-18 16:43:16.314785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8968edd7b050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_active_cat_diff', ['is_active', 'category_id', 'difficulty'], unique=False)

    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.create_index('ix_test_answers_attempt_question', ['attempt_id', 'question_id'], unique=False)

    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_test_attempts_user_date', ['user_id', 'completed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_test_attempts_user_date')

    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_test_answers_attempt_question')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_active_cat_diff')

    # ### end Alembic commands ###
